# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ESchoolBagStudent' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SVProgressHUD', '~> 2.0.4'

  # Pods for ESchoolBagStudent

end
